{% set name = "venn-abers" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/venn-abers-{{ version }}.tar.gz
  sha256: ebeb853fe102015852afcab2fafa0b47268e43b480ed447578f4644e216b8bce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scikit-learn
    - pandas

test:
  imports:
    - venn_abers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ip200/venn-abers
  summary: Venn-ABERS calibration package
  license: MIT
  license_file: LICENSE.TXT

extra:
  recipe-maintainers:
    - ip200
