{% set name = "venn-abers" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 47d86a2b8e388e15b5c0bf2e2419c3dad91f11750c614dbf72eea6e38d11ca95

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scikit-learn
    - pandas

test:
  imports:
    - venn_abers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ip200/venn-abers
  summary: Venn-ABERS calibration package
  license: MIT
  license_file: LICENSE.TXT

extra:
  recipe-maintainers:
    - ip200
